server:
  port: 8888
  contextPath: /wechat-service
  address: 0.0.0.0

com:
  github:
    steven:
      weChatConfig:
        token: token
        appId: appId
        appSercret: appSercret
      imageDir: /root/
      keywork: 妹纸

logging:
  level:
    root: info
    org.springframework.web: info
    org.apache.ibatis: info

  path: "./logs"