server:
  port: 8888
  contextPath: /wechat-service
  address: 0.0.0.0

com:
  github:
    steven:
      weChatConfig:
        token: stevencode
        appId: wx9f42a2308dd6d508
        appSercret: f3a8a1b212866682dea5f9b13d89680c
      imageDir: /root/pythonProject/meizi
      keyword: 妹子

logging:
  level:
    root: info
    org.springframework.web: info
    org.apache.ibatis: info
    org.apache.http: info

  path: "./logs"